### ISSUE TITLE
[Enhancement] Ignore bad names an item

### ISSUE THREAD

**Issue by ghost** [Musician101/ItemBank#1]
Hello. Add the plug-in function: if the name of the item is not recognized (for example, placed an item in the database server with the mod "TEST", I went on the server where this mod is not) replace it with air and prohibit taking.

Currently, if an item name that is not recognized by write error: http://pastebin.com/HxwtuEKz (Item Bank v2.4.1)

Sorry for my english, I'm from another country.

P.S I really need to improve this, and I hope that my proposal will be carried out soon.

**Comment by Musician101** [comment]
If I am to understand this correctly, you are using this on a Bukkit/Forge hybrid server?

**Comment by ghost** [comment]
Yes, KCauldron

**Comment by Musician101** [comment]
Unfortunately the version of ItemBank you're using was coded only to work with Bukkit.
